# Generated by Django 6.1.1 on 2026-10-06 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback', models.TextField()),
                ('data_avaliacao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('area', models.TextField()),
                ('prazo', models.IntegerField()),
                ('tecnologias', models.TextField()),
                ('objetivo', models.TextField()),
                ('requisitos', models.TextField()),
                ('entregaveis', models.TextField()),
                ('criterios_avaliativos', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'db_table': 'desafio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('contato', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interesseprofissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name': 'Interesse Profissional',
                'verbose_name_plural': 'Interesses Profissionais',
                'db_table': 'interesseprofissional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_adesao', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('entrega_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'db_table': 'participacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfilestudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=90)),
                ('instituicao', models.CharField(max_length=90)),
                ('biografia', models.TextField()),
                ('competencias', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Estudante',
                'verbose_name_plural': 'Perfis Estudantes',
                'db_table': 'perfilestudante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reconhecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField()),
                ('competencias', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Reconhecimento',
                'verbose_name_plural': 'Reconhecimentos',
                'db_table': 'reconhecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('senha_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
