# Generated by Django 6.1.1 on 2026-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listreconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=33, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Lista de Reconhecimento',
                'verbose_name_plural': 'Listas de Reconhecimento',
                'db_table': 'listreconhecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'db_table': 'niveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusentrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name': 'Status de Entrega',
                'verbose_name_plural': 'Status de Entregas',
                'db_table': 'statusentrega',
                'managed': False,
            },
        ),
    ]
