# Generated by Django 6.1.1 on 2026-10-07 02:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


# The original models were unmanaged, so fresh databases never received these tables.
def ensure_domain_schema(apps, schema_editor):
    connection = schema_editor.connection
    domain_models = tuple(
        apps.get_model('desafio', model_name)
        for model_name in (
            'Usuario',
            'Empresa',
            'Niveis',
            'Statusentrega',
            'Perfilestudante',
            'Desafio',
            'Participacao',
            'Avaliacao',
            'Reconhecimento',
            'Interesseprofissional',
            'Listreconhecimento',
        )
    )
    existing_tables = set(connection.introspection.table_names())

    for model in domain_models:
        table = model._meta.db_table
        if table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(table)
            continue

        with connection.cursor() as cursor:
            columns = {
                column.name: column
                for column in connection.introspection.get_table_description(cursor, table)
            }
        for field in model._meta.local_fields:
            if field.column not in columns:
                schema_editor.add_field(model, field)

    for model in domain_models:
        for constraint in model._meta.constraints:
            with connection.cursor() as cursor:
                constraints = connection.introspection.get_constraints(
                    cursor,
                    model._meta.db_table,
                )
            if constraint.name not in constraints:
                schema_editor.add_constraint(model, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_listreconhecimento_niveis_statusentrega'),
    ]

    operations = [
        migrations.RunPython(ensure_domain_schema, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='desafio',
            options={'verbose_name': 'Desafio', 'verbose_name_plural': 'Desafios'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='interesseprofissional',
            options={'verbose_name': 'Interesse Profissional', 'verbose_name_plural': 'Interesses Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='listreconhecimento',
            options={'verbose_name': 'Lista de Reconhecimento', 'verbose_name_plural': 'Listas de Reconhecimento'},
        ),
        migrations.AlterModelOptions(
            name='niveis',
            options={'verbose_name': 'Nível', 'verbose_name_plural': 'Níveis'},
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'verbose_name': 'Participação', 'verbose_name_plural': 'Participações'},
        ),
        migrations.AlterModelOptions(
            name='perfilestudante',
            options={'verbose_name': 'Perfil Estudante', 'verbose_name_plural': 'Perfis Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='reconhecimento',
            options={'verbose_name': 'Reconhecimento', 'verbose_name_plural': 'Reconhecimentos'},
        ),
        migrations.AlterModelOptions(
            name='statusentrega',
            options={'verbose_name': 'Status de Entrega', 'verbose_name_plural': 'Status de Entregas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.CreateModel(
            name='TokenAutenticacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave_hash', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='desafio.usuario')),
            ],
            options={
                'db_table': 'token_autenticacao',
            },
        ),
    ]
